version: '3.8'
services:
  web:
    container_name: webhook_wp
    build: .
    ports:
      - "8002:8002"
    volumes:
      - ./:/app
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    networks:
      network:
        ipv4_address: 172.18.0.12
    command: uvicorn wsgi:app --host 0.0.0.0 --port 8002 --workers 4

networks:
  network:
    driver: bridge
    name: proxy
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
